markdown: kramdown
permalink: /:title/
url: https://yigubigu.github.io/
name: yigubigu
author: yigubigu
qq: 
email: 
duoshuo: 
beian: 
cnzz: 
weibo: 
github: yigubigu
safe: true
paginate: 20
about: "这里是 yigubigu，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
